# Generated by Django 3.2.16 on 2022-12-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='postcode',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='town_city',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_line',
            new_name='physical_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_line2',
        ),
    ]
