# Generated by Django 3.2.16 on 2022-12-17 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_address_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoptions',
            name='transporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.customuser'),
            preserve_default=False,
        ),
    ]
