# Generated by Django 3.2.16 on 2022-12-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_deliveryoptions_transporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryoptions',
            name='order',
        ),
    ]
