# Generated by Django 3.2.16 on 2022-12-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_remove_deliveryoptions_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='customer',
            field=models.BooleanField(default=True),
        ),
    ]
