# Generated by Django 3.2.16 on 2022-12-21 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity_at_hand',
        ),
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
