# Generated by Django 3.2.16 on 2022-12-13 10:24

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20221202_1024'),
        ('order', '0002_alter_payment_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.address'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='MWK', max_digits=14),
        ),
    ]
