# Generated by Django 3.2.16 on 2022-12-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_payment_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
    ]
