# Generated by Django 3.2.16 on 2022-12-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_payment_order_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customer',
        ),
    ]
