# Generated by Django 3.2.16 on 2022-12-15 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_orderitem_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_reference',
        ),
    ]
