# Generated by Django 3.2.16 on 2022-12-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_order_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
