# Generated by Django 3.2.16 on 2022-12-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_delivery_opt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_opt',
            new_name='delivery_option',
        ),
    ]
